#include "PluginAuthoringBackend.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <iostream>
#include <regex>

#include "PluginManager.h"

namespace bbfx {

namespace fs = std::filesystem;

std::string PluginAuthoringBackend::slugify(const std::string& name) {
    std::string out;
    out.reserve(name.size());
    bool prevDash = false;
    for (char c : name) {
        if (std::isalnum(static_cast<unsigned char>(c))) {
            out += static_cast<char>(std::tolower(c));
            prevDash = false;
        } else if (c == '.' || c == '-') {
            if (!prevDash) { out += c; prevDash = true; }
        } else if (std::isspace(static_cast<unsigned char>(c)) || c == '_') {
            if (!prevDash && !out.empty()) { out += '-'; prevDash = true; }
        }
    }
    while (!out.empty() && (out.back() == '-' || out.back() == '.')) out.pop_back();
    return out;
}

bool PluginAuthoringBackend::isValidId(const std::string& id) {
    // Must match the JSON-schema pattern used by PluginValidator
    // (`^[a-z0-9-]+\.[a-z0-9-]+$`) — exactly one dot separating two
    // kebab-case segments.
    static const std::regex re("^[a-z0-9-]+\\.[a-z0-9-]+$");
    return std::regex_match(id, re);
}

std::vector<std::string> PluginAuthoringBackend::detectPermissions(
    const std::string& luaSource)
{
    static const std::pair<const char*, const char*> kMap[] = {
        {"bbfx.midi",         "midi"},
        {"bbfx.osc",          "osc"},
        {"bbfx.artnet",       "artnet"},
        {"bbfx.textureShare", "texture-share"},
        {"bbfx.gamepad",      "gamepad"},
        {"bbfx.joystick",     "gamepad"},
        {"bbfx.http",         "network"},
        {"bbfx.websocket",    "network"},
        {"bbfx.fs",           "fs"},
        {"bbfx.ui",           "ui"},
        {"bbfx.scene",        "scene"},
        {"bbfx.models",       "models"},
        {"bbfx.audio",        "audio"},
    };
    std::vector<std::string> out;
    for (auto& kv : kMap) {
        if (luaSource.find(kv.first) != std::string::npos) {
            // Avoid duplicates (e.g. gamepad + joystick both map to "gamepad").
            if (std::find(out.begin(), out.end(), kv.second) == out.end()) {
                out.emplace_back(kv.second);
            }
        }
    }
    return out;
}

namespace {

nlohmann::json buildManifest(const PluginAuthoringBackend::Metadata& meta) {
    using nlohmann::json;
    json j;
    j["id"]           = meta.id;
    j["name"]         = meta.name.empty() ? meta.id : meta.name;
    j["version"]      = meta.version;
    j["type"]         = (meta.category == "Scene" || meta.category == "OutputTemplate")
                          ? meta.category
                          : std::string("Node");
    j["bbfx_version"] = meta.bbfxVersion;
    j["description"]  = meta.description;
    j["category"]     = meta.category;
    j["license"]      = meta.license;
    j["entry"]        = "init.lua";
    json author;
    author["name"] = meta.author.empty() ? std::string("BBFx Studio user") : meta.author;
    j["author"]    = author;
    if (!meta.tags.empty())        j["tags"]        = meta.tags;
    if (!meta.permissions.empty()) j["permissions"] = meta.permissions;
    return j;
}

void writeText(const fs::path& p, const std::string& body) {
    std::ofstream f(p, std::ios::binary);
    f.write(body.data(), static_cast<std::streamsize>(body.size()));
}

} // anonymous

fs::path PluginAuthoringBackend::writePlugin(
    const fs::path& destRoot,
    const Metadata& meta,
    const std::string& initLuaBody,
    const std::vector<std::pair<std::string, std::string>>& extraFiles)
{
    if (meta.id.empty()) {
        std::cerr << "[PluginAuthoringBackend] writePlugin: empty id" << std::endl;
        return {};
    }
    if (!isValidId(meta.id)) {
        std::cerr << "[PluginAuthoringBackend] writePlugin: invalid id '"
                   << meta.id << "'" << std::endl;
        return {};
    }
    std::error_code ec;
    fs::path pluginDir = destRoot / meta.id;
    fs::create_directories(pluginDir, ec);
    if (ec) {
        std::cerr << "[PluginAuthoringBackend] cannot create " << pluginDir
                   << ": " << ec.message() << std::endl;
        return {};
    }
    try {
        // manifest.json
        writeText(pluginDir / "manifest.json",
                    buildManifest(meta).dump(2) + "\n");
        // init.lua
        writeText(pluginDir / "init.lua",
                    initLuaBody.empty() ? std::string("return {}\n") : initLuaBody);
        // README.md (template)
        std::string readme = "# " + meta.name + "\n\n" + meta.description + "\n\n"
            + "**Author:** " + meta.author + "\n\n"
            + "**License:** " + meta.license + "\n\n"
            + "Generated by BBFx Studio Plugin Authoring.\n";
        writeText(pluginDir / "README.md", readme);
        // Copy resources
        for (auto& [rel, src] : extraFiles) {
            if (rel.empty() || src.empty()) continue;
            fs::path dst = pluginDir / rel;
            fs::create_directories(dst.parent_path(), ec);
            fs::copy_file(src, dst,
                           fs::copy_options::overwrite_existing, ec);
            if (ec) {
                std::cerr << "[PluginAuthoringBackend] copy " << src << " -> "
                           << dst << " failed: " << ec.message() << std::endl;
            }
        }
    } catch (const std::exception& e) {
        std::cerr << "[PluginAuthoringBackend] writePlugin failed: "
                   << e.what() << std::endl;
        // Rollback: best-effort remove the partially-created directory.
        fs::remove_all(pluginDir, ec);
        return {};
    }
    return pluginDir;
}

fs::path PluginAuthoringBackend::exportScenePreset(
    const Metadata& inMeta, const nlohmann::json& sceneJson)
{
    Metadata meta = inMeta;
    if (meta.category != "Scene") meta.category = "Scene";
    // Auto-set permission `scene` since the init.lua restores scene state.
    if (std::find(meta.permissions.begin(), meta.permissions.end(),
                   std::string("scene")) == meta.permissions.end()) {
        meta.permissions.emplace_back("scene");
    }
    std::string init =
        "-- v3.5 Lot S — Scene preset plugin.\n"
        "-- Restores a captured scene state when enabled.\n"
        "local scene = " + sceneJson.dump() + "\n"
        "return {\n"
        "    onEnable = function()\n"
        "        if bbfx.scene and bbfx.scene.applyPreset then\n"
        "            bbfx.scene.applyPreset(scene)\n"
        "        else\n"
        "            print('[" + meta.id + "] bbfx.scene.applyPreset not available')\n"
        "        end\n"
        "    end,\n"
        "    capture = scene,\n"
        "}\n";
    return writePlugin(PluginManager::instance().getUserPluginsDir(),
                        meta, init, {});
}

fs::path PluginAuthoringBackend::exportOutputTemplate(
    const Metadata& inMeta, const nlohmann::json& outputJson)
{
    Metadata meta = inMeta;
    if (meta.category != "OutputTemplate") meta.category = "OutputTemplate";
    // Output manager config restoration needs `scene` perm (applies
    // cameras + render target changes).
    if (std::find(meta.permissions.begin(), meta.permissions.end(),
                   std::string("scene")) == meta.permissions.end()) {
        meta.permissions.emplace_back("scene");
    }
    std::string init =
        "-- v3.5 Lot S — Output template plugin.\n"
        "local outputs = " + outputJson.dump() + "\n"
        "return {\n"
        "    onEnable = function()\n"
        "        if bbfx.output and bbfx.output.applyTemplate then\n"
        "            bbfx.output.applyTemplate(outputs)\n"
        "        else\n"
        "            print('[" + meta.id + "] bbfx.output.applyTemplate not available')\n"
        "        end\n"
        "    end,\n"
        "    capture = outputs,\n"
        "}\n";
    return writePlugin(PluginManager::instance().getUserPluginsDir(),
                        meta, init, {});
}

fs::path PluginAuthoringBackend::exportSubgraph(
    const Metadata& inMeta, const nlohmann::json& subgraphJson)
{
    Metadata meta = inMeta;
    if (meta.category.empty()) meta.category = "Node";
    std::string init =
        "-- v3.5 Lot S — Node subgraph plugin.\n"
        "-- Re-instantiates a captured subgraph on each enable.\n"
        "local spec = " + subgraphJson.dump() + "\n"
        "return {\n"
        "    onEnable = function()\n"
        "        for _, n in ipairs(spec.nodes or {}) do\n"
        "            if bbfx.createNode then bbfx.createNode(n.type, n.name) end\n"
        "        end\n"
        "        for _, l in ipairs(spec.links or {}) do\n"
        "            if bbfx.link then bbfx.link(l.src, l.srcPort, l.dst, l.dstPort) end\n"
        "        end\n"
        "    end,\n"
        "    spec = spec,\n"
        "}\n";
    return writePlugin(PluginManager::instance().getUserPluginsDir(),
                        meta, init, {});
}

} // namespace bbfx
