#pragma once

#include <nlohmann/json.hpp>
#include <map>
#include <string>

namespace sol { class state; }

namespace bbfx {

/// AssetManifest — versioned asset registry indexed by content hash.
///
/// v3.5.2 final:
///   - Hash is SHA-256 (RFC 6234, 64 hex chars). Self-contained
///     implementation in `Sha256.h/.cpp` — no OpenSSL dependency.
///     Cryptographically secure, suitable for content-addressed caches
///     and downloaded-asset verification.
///   - Cache root: ~/.bbfx/cache/<hash[0..1]>/<hash>  (git-objects style).
///   - HTTPS download via `cpr` (already in vcpkg from v3.5) — see
///     `downloadToCache()` for the verified-download path.
class AssetManifest {
public:
    struct Entry {
        std::string name;        // logical name ("alien_cells")
        std::string filename;    // local path relative to project root
        std::string hash;        // 64-hex-char SHA-256
        size_t      size_bytes = 0;
        std::string type;        // "texture" / "video" / "audio" / "mesh"
        std::string source_url;  // optional HTTPS for re-download
        // v3.5.2 Sprint S7 Lot Z — extended metadata for Heritage Pack browsing.
        std::string category;    // "organic" / "cosmic" / "geometric" / "mask" / "gray_pair" / "video"
        std::string license;     // "CC0" / "CC-BY" / "CC-BY-SA" / ""
        std::string author;      // "ambientCG" / "polyhaven" / ...
    };

    static AssetManifest& instance();

    /// Compute the SHA-256 hash (64 hex chars) of a file's full contents.
    /// Returns empty string on read failure.
    static std::string computeFileHash(const std::string& filepath);

    /// Compute the SHA-256 hash (64 hex chars) of a memory buffer (for tests).
    static std::string computeBufferHash(const void* data, size_t size);

    /// User home cache root: <home>/.bbfx/cache/  (created lazily on first use).
    static std::string getCacheRoot();

    /// Path inside the cache for a given hash: <root>/<hash[0..1]>/<hash>.
    static std::string getCachePath(const std::string& hash);

    /// True if a file matching the hash already exists in the local cache.
    static bool isCached(const std::string& hash);

    /// Download the URL into the local cache and verify SHA-256 against the
    /// expected hash. Refuses non-HTTPS URLs (RFC strict). Returns the local
    /// cache path on success, empty string on failure (network, hash mismatch,
    /// 500 MB size cap exceeded).
    /// Synchronous (blocks). For async / progress-bar download, wrap in a
    /// std::async at the call site.
    static std::string downloadToCache(const std::string& url,
                                       const std::string& expectedHash,
                                       std::string& outError);

    /// Maximum allowed download size, in bytes. Hard limit to avoid runaway
    /// downloads. Configurable via setter; default 500 MB.
    static size_t getMaxDownloadBytes();
    static void   setMaxDownloadBytes(size_t bytes);

    /// Resolve a logical asset name to its OGRE-friendly filename (the
    /// `filename` field of the manifest entry). The Engine registers the
    /// AssetCache directory as a recursive FileSystem ResourceLocation, so
    /// OGRE TextureManager / MaterialManager can resolve this name directly.
    ///
    /// Returns empty string if name unknown in the loaded manifest.
    std::string resolve(const std::string& name) const;

    /// Resolves the logical name AND ensures the texture is loaded into
    /// OGRE's TextureManager (under group "AssetCache"). Use when you need
    /// the asset to be immediately ready for `TextureUnitState::setTexture`.
    /// Returns empty string if the name is unknown; returns the filename
    /// even if the load fails (graceful — OGRE will report a clear error).
    std::string resolveAndLoad(const std::string& name) const;

    // CRUD
    void addEntry(const Entry& e);
    bool removeEntry(const std::string& name);
    const Entry* getEntry(const std::string& name) const;
    size_t entryCount() const { return mEntries.size(); }
    void clearAll();

    /// v3.5.2 Sprint S7 Lot Z — read-only access to all entries (for UI iteration).
    const std::map<std::string, Entry>& getEntries() const { return mEntries; }

    // Persistence (JSON, suitable for storing inside extraJson["asset_manifest"])
    nlohmann::json toJson() const;
    void fromJson(const nlohmann::json& j);

    /// Load entries from a Lua file that returns a table of entries.
    /// Format (auto-generated by `tools/asset_pipeline.py manifest`):
    ///   return {
    ///     ["alien_cells"] = {
    ///       file        = "alien_cells.jpg",
    ///       hash_sha256 = "abc123...",        -- 64 hex chars
    ///       size_bytes  = 524288,
    ///       type        = "texture",          -- "texture" | "video" | ...
    ///       license     = "CC0",
    ///       source_url  = "https://cdn.../...",
    ///       width = 1024, height = 1024,
    ///     },
    ///     ...
    ///   }
    /// Existing entries with the same name are overwritten. Returns the
    /// number of entries successfully added (0 on file/parse error — does
    /// not throw, errors are logged to stderr).
    size_t loadFromLuaFile(sol::state& lua, const std::string& luaPath);

private:
    std::map<std::string, Entry> mEntries;
};

} // namespace bbfx
