-- ============================================================================
-- BBFx v3.5 Lot S — Plugin Authoring Backend
-- ============================================================================
-- Coverage : I-1492..I-1503 (backend surface)
--   * bbfx.authoring.slugify        — id slugification
--   * bbfx.authoring.isValidId      — id pattern check
--   * bbfx.authoring.detectPermissions — heuristic Lua source scan
--   * bbfx.authoring.writePlugin    — generic manifest + init.lua writer
--   * bbfx.authoring.exportSubgraph
--   * bbfx.authoring.exportScenePreset
--   * bbfx.authoring.exportOutputTemplate
-- Each exporter writes a real plugin directory under the user plugins
-- dir and we verify the resulting manifest + init.lua.
-- ============================================================================

print("\n================================================================")
print("  BBFx v3.5 Lot S — Plugin Authoring Backend")
print("================================================================\n")

local P, F = 0, 0
local fails = {}
local function check(id, name, cond, extra)
    if cond then
        P = P + 1; print("  PASS  " .. id .. " " .. name)
    else
        F = F + 1
        print("  FAIL  " .. id .. " " .. name .. (extra and ("  [" .. tostring(extra) .. "]") or ""))
        table.insert(fails, id .. " " .. name)
    end
end

-- ── Namespace ─────────────────────────────────────────────────────────
check("S-001", "bbfx.authoring namespace exists",
      type(bbfx.authoring) == "table")
for _, fn in ipairs({"slugify","isValidId","detectPermissions","writePlugin",
                     "exportSubgraph","exportScenePreset","exportOutputTemplate"}) do
    check("S-002." .. fn, "bbfx.authoring." .. fn .. " is a function",
          type(bbfx.authoring[fn]) == "function")
end

-- ── slugify (I-1494) ───────────────────────────────────────────────────
check("S-010", "slugify('Plasma Wave!') == 'plasma-wave'",
      bbfx.authoring.slugify("Plasma Wave!") == "plasma-wave")
check("S-011", "slugify normalizes underscores",
      bbfx.authoring.slugify("my_cool_plugin") == "my-cool-plugin")
check("S-012", "slugify preserves dots",
      bbfx.authoring.slugify("my.plugin.name") == "my.plugin.name")

-- ── isValidId ─────────────────────────────────────────────────────────
check("S-013", "isValidId accepts kebab",
      bbfx.authoring.isValidId("foo-bar.plugin") == true)
check("S-014", "isValidId rejects spaces",
      bbfx.authoring.isValidId("NOT VALID") == false)
check("S-015", "isValidId rejects uppercase",
      bbfx.authoring.isValidId("MyPlugin") == false)

-- ── detectPermissions (I-1496) ─────────────────────────────────────────
local perms = bbfx.authoring.detectPermissions(
    "local cc = bbfx.midi.getCC(1,1); " ..
    "local r = bbfx.http.get('http://x'); " ..
    "bbfx.ui.registerPanel('p', function() end)")
local found = {}
for _, p in ipairs(perms) do found[p] = true end
check("S-020", "detectPermissions finds midi", found["midi"] == true)
check("S-021", "detectPermissions finds network", found["network"] == true)
check("S-022", "detectPermissions finds ui", found["ui"] == true)
check("S-023", "detectPermissions ignores absent namespaces",
      found["artnet"] == nil)

-- ── writePlugin (I-1498) ───────────────────────────────────────────────
local meta = {
    id          = "test-lot-s.basic",
    name        = "Lot S Basic Test",
    version     = "0.1.0",
    author      = "bbfx tests",
    description = "Write-plugin round-trip test",
    category    = "Custom",
    tags        = { "test", "lotS" },
    permissions = { "fs" },
}
local path = bbfx.authoring.writePlugin(meta,
    "-- Generated by Lot S test\nreturn { info = 'ok' }\n", nil)
check("S-030", "writePlugin returns a path string",
      type(path) == "string" and #path > 0)
-- Verify the files actually exist.
local manifestPath = path .. "/manifest.json"
local initLuaPath  = path .. "/init.lua"
local readmePath   = path .. "/README.md"
check("S-031", "manifest.json written",
      bbfx.fs.exists(manifestPath))
check("S-032", "init.lua written",
      bbfx.fs.exists(initLuaPath))
check("S-033", "README.md written",
      bbfx.fs.exists(readmePath))

-- Decode manifest and check fields.
local mBody = bbfx.fs.readFile(manifestPath)
check("S-034", "manifest is non-empty",
      type(mBody) == "string" and #mBody > 0)
local m = bbfx.json.decode(mBody)
check("S-035", "manifest.id round-trips",
      m.id == "test-lot-s.basic")
check("S-036", "manifest.permissions roundtripped",
      type(m.permissions) == "table" and m.permissions[1] == "fs")
check("S-037", "manifest.tags roundtripped",
      type(m.tags) == "table" and m.tags[1] == "test" and m.tags[2] == "lotS")

-- Verify init.lua body
local initBody = bbfx.fs.readFile(initLuaPath)
check("S-038", "init.lua contains the generated body",
      type(initBody) == "string" and initBody:find("return {") ~= nil)

-- ── exportSubgraph (I-1493, I-1498) ────────────────────────────────────
local subPath = bbfx.authoring.exportSubgraph(
    { id = "test-lot-s.subgraph", name = "Subgraph", category = "Node" },
    { nodes = { { type = "MathNode", name = "n1" } },
      links = {} })
check("S-040", "exportSubgraph returns a path",
      type(subPath) == "string" and #subPath > 0)
check("S-041", "exportSubgraph init.lua contains spec",
      bbfx.fs.readFile(subPath .. "/init.lua"):find("MathNode") ~= nil)

-- ── exportScenePreset (I-1499) ─────────────────────────────────────────
local scenePath = bbfx.authoring.exportScenePreset(
    { id = "test-lot-s.scene", name = "Scene Preset" },
    { camera = { rotX = 0.5 }, warp = { enabled = true } })
check("S-050", "exportScenePreset returns a path",
      type(scenePath) == "string" and #scenePath > 0)
local sceneManifest = bbfx.json.decode(bbfx.fs.readFile(scenePath .. "/manifest.json"))
check("S-051", "scene manifest has category 'Scene'",
      sceneManifest.category == "Scene")
check("S-052", "scene manifest has 'scene' permission auto-added",
      type(sceneManifest.permissions) == "table" and
      (function()
          for _, p in ipairs(sceneManifest.permissions) do
              if p == "scene" then return true end
          end
          return false
      end)())

-- ── exportOutputTemplate (I-1500) ──────────────────────────────────────
local outputPath = bbfx.authoring.exportOutputTemplate(
    { id = "test-lot-s.output", name = "Output Template" },
    { { id = 0, width = 1920, height = 1080 },
      { id = 1, width = 1920, height = 1080 } })
check("S-060", "exportOutputTemplate returns a path",
      type(outputPath) == "string" and #outputPath > 0)
local outputManifest = bbfx.json.decode(bbfx.fs.readFile(outputPath .. "/manifest.json"))
check("S-061", "output manifest has category 'OutputTemplate'",
      outputManifest.category == "OutputTemplate")

-- ── Cleanup ───────────────────────────────────────────────────────────
local function rmdir(p)
    os.execute('rmdir /S /Q "' .. p:gsub("/", "\\") .. '" 2>NUL')
    os.execute('rm -rf "' .. p .. '" 2>/dev/null')
end
rmdir(path)
rmdir(subPath)
rmdir(scenePath)
rmdir(outputPath)

-- ── Non-regression : Lot R/Q/P bindings still reachable ────────────────
check("S-099.a", "bbfx.sdf.sphere still reachable",
      type(bbfx.sdf.sphere) == "function")
check("S-099.b", "bbfx.fractals.mandelbrot still reachable",
      type(bbfx.fractals.mandelbrot) == "function")
check("S-099.c", "bbfx.media.openVideo still reachable",
      type(bbfx.media.openVideo) == "function")

print("\n--------------------------------------------------------------")
print(string.format("  Lot S Tests: %d PASS, %d FAIL", P, F))
print("--------------------------------------------------------------\n")

if F > 0 then
    for _, n in ipairs(fails) do print("  - " .. n) end
    error("Lot S tests FAILED")
end

os.exit(0)
